<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e6fd9d010a37502b05b1d46
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbtesiscroc_dbManager.php';
	
/*
 * SCHEMA DB coppia
 * 
	{
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		gioca: {
			type: Schema.ObjectId,
			ref : "coppia"
		},
		giocano: {
			type: Schema.ObjectId,
			ref : "coppia"
		},
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/coppia',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		
		'gioca' => isset($body->gioca)?$body->gioca:'',

		'giocano' => isset($body->giocano)?$body->giocano:'',
	);

	$obj = makeQuery("INSERT INTO coppia (_id , gioca , giocano )  VALUES ( null , :gioca , :giocano   )", $params, false);
        
	
	echo json_encode($body);
	
});
	
//CRUD - GET ONE
	
$app->get('/coppia/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM coppia WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	

//CRUD - EDIT

$app->post('/coppia/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'gioca'      => isset($body->gioca)?$body->gioca:'' 
,
		'giocano'      => isset($body->giocano)?$body->giocano:'' 
	);

	$obj = makeQuery("UPDATE coppia SET  , gioca=:gioca , giocano=:giocano  WHERE _id = :id LIMIT 1", $params, false);
        
	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>